name: Build ZMK firmware
on:
  workflow_dispatch: # can be triggered manually
  push:
    paths:
      - "build.yaml"
      - "config/*.keymap"
      - "config/*.conf"
      - "config/west.yml"
jobs:
  build:
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@v0.3
